spring.application.name=guias-despacho

logging.level.root=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework=INFO

# --- CONEXIÓN A BASE DE DATOS ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@duocuc_tp?TNS_ADMIN=/app/wallet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ADMIN}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aa.123654789.AA}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- CONFIGURACIÓN JPA / HIBERNATE ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
# Esto creará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# --- CONFIGURACIÓN POOL CONEXIONES ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

server.port=8080

# --- AWS S3 ---
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:}
cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN:}
cloud.aws.region.static=${AWS_REGION:us-east-1}
cloud.aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:}

# Evitar conflicto con S3Client manual en StorageConfig
spring.autoconfigure.exclude=io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

# --- ALMACENAMIENTO TEMPORAL EFS (montado en /mnt/efs en EC2) ---
storage.efs.base-path=${EFS_BASE_PATH:/app/efs}